### ISSUE TITLE
Include sub directories

### ISSUE THREAD

**Issue by DerZade** [flother/spreet#42]
I have a the following directory structure:
```
input
├── category1
│   ├── foo.svg
│   └── bar.svg
├── baz.svg
└── category2
    ├── foo.svg
    └── bar.svg
```

When calling `spreet` i only get a spritesheet including `baz.svg`. Instead I would like to include all files with the following ids: `category1/foo`, `category1/bar`, `baz`, `category2/foo`, `category2/bar`.

As far as I can tell this is not possible at the moment. Would you be open to a PR which adds this functionality?
If yes, should this this be disabled by default and behind an option (`--deep` or something)?

**Comment by flother** [comment]
I actually had this functionality in the early days of Spreet, but I took it out in d4eb3d758e04 because it didn't match spritezero-cli's behaviour. (It could, in theory, have broken things for people, and I wanted Spreet to be a drop-in replacement for spritezero-cli.) But I like the idea of adding it back and putting it behind a command-line argument. Perhaps `--recursive` would be a good name for it.

One thing I don't think I had was name prefixes, so `dir1/foo.svg` and `dir2/foo.svg` would both have the id `foo` in the sprite index. That would need fixing. I'd certainly be open to a PR based on the old code but updated to include prefixes. Go for it!
